name: random_password_generator
description: A Random password generator

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+10

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.3
  google_fonts: ^2.1.0
  flutter_bloc: ^8.0.1
  intl: ^0.17.0
  shared_preferences: ^2.0.7
  logger: ^1.1.0
  equatable: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.1.4
  mockito: ^5.0.16
  flutter_lints: ^1.0.4
  bloc_test: ^9.0.2
flutter:
  uses-material-design: true
  generate: true